*&---------------------------------------------------------------------*
*& Report YDJ_SCREEN_MODIFY_DEMO
*&---------------------------------------------------------------------*
*& LOOP AT SCREEN / MODIFY SCREEN - the four documented ways a screen
*& modification silently does nothing.
*&
*&   1. THE PBO RESET     -> every property is reset to its STATIC
*&                           value at the start of each PBO, so a
*&                           MODIFY SCREEN in PAI never reaches the
*&                           screen, and a hide needs no matching
*&                           un-hide branch.
*&   2. THE name RULE     -> if wa-name is not the name of the CURRENT
*&                           element the statement is 'not executed'.
*&                           No exception, no sy-subrc, no message.
*&   3. active WINS       -> setting active = '0' forces input/output
*&                           to 0 and invisible to 1, and any other
*&                           values in those three are IGNORED.
*&   4. required = '2'    -> looks exactly like a mandatory field and
*&                           is never checked.
*&
*& Self-contained: only this report's own selection screen is touched.
*& No database access of any kind, no COMMIT.
*&
*& How to run it: execute, then switch the radio button. The block
*& marked MODIF ID DYN disappears and comes back. Press F8 to reach
*& START-OF-SELECTION, which prints what LOOP AT SCREEN actually
*& enumerated on the LAST PBO - including the generated element names
*& of the SELECT-OPTIONS, which are NOT a documented contract (see the
*& README). Read them off your own system rather than hard-coding
*& them.
*&---------------------------------------------------------------------*
REPORT ydj_screen_modify_demo.

" sscrfields is needed to read the function code raised by
" USER-COMMAND. The keyword documentation recommends sscrfields-ucomm
" over sy-ucomm, which is not guaranteed to be correct here.
TABLES sscrfields.

TYPES: BEGIN OF ty_elem,
         name   TYPE screen-name,
         group1 TYPE screen-group1,
         input  TYPE screen-input,
         output TYPE screen-output,
         invis  TYPE screen-invisible,
         active TYPE screen-active,
       END OF ty_elem.

DATA gt_elem   TYPE STANDARD TABLE OF ty_elem WITH EMPTY KEY.
DATA gv_passes TYPE i.
" Reference field for SELECT-OPTIONS ... FOR. It only supplies the type
" and length of the low/high columns; it is never read by the demo.
DATA gv_carrid TYPE c LENGTH 3.

*&---------------------------------------------------------------------*
*& The selection screen. MODIF ID is the whole reason this topic is
*& usable: it stamps a 3-character group into screen-group1 for EVERY
*& element a declaration generates, so the loop below never has to
*& guess at generated names.
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-b01.
  PARAMETERS p_all  RADIOBUTTON GROUP g1 DEFAULT 'X' USER-COMMAND uc1.
  PARAMETERS p_some RADIOBUTTON GROUP g1.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-b02.
  " Every element generated by this SELECT-OPTIONS carries group1 = DYN:
  " both input fields, the label and the multiple-selection pushbutton.
  SELECT-OPTIONS s_carr FOR gv_carrid MODIF ID dyn.
  PARAMETERS     p_note TYPE c LENGTH 20 MODIF ID dyn.
  " Deliberately NOT in group DYN, to show the loop skipping it.
  PARAMETERS     p_keep TYPE c LENGTH 20.
SELECTION-SCREEN END OF BLOCK b2.

*&---------------------------------------------------------------------*
*& AT SELECTION-SCREEN OUTPUT is the PBO of the selection screen.
*& This is the ONLY event where a modification reaches the display.
*&---------------------------------------------------------------------*
AT SELECTION-SCREEN OUTPUT.

  gv_passes = gv_passes + 1.
  CLEAR gt_elem.

  LOOP AT SCREEN INTO DATA(ls_screen).

    " Record what the runtime actually enumerated, for START-OF-SELECTION.
    APPEND VALUE ty_elem( name   = ls_screen-name
                          group1 = ls_screen-group1
                          input  = ls_screen-input
                          output = ls_screen-output
                          invis  = ls_screen-invisible
                          active = ls_screen-active ) TO gt_elem.

    " Trap 1 in action: there is no ELSE branch making DYN visible
    " again. It does not need one. The runtime resets every property
    " to its static value before this event runs, so the fields are
    " already visible on every pass and we only ever take things away.
    IF ls_screen-group1 = 'DYN' AND p_some = 'X'.

      " Trap 3: active = '0' is the blunt instrument. It drives
      " input/output to 0 and invisible to 1 by itself, and it makes
      " any value we might also write into those three irrelevant.
      ls_screen-active = '0'.

      " Trap 2: MODIFY SCREEN is silently skipped unless wa-name is
      " the name of the element of THIS loop pass. We never touched
      " ls_screen-name, so it still holds the right value - which is
      " exactly why the bug is so easy to introduce: clearing the work
      " area, or filling it from a template row, disables the
      " statement with no diagnostic at all.
      MODIFY SCREEN FROM ls_screen.

    ENDIF.

  ENDLOOP.

*&---------------------------------------------------------------------*
*& Trap 2 demonstrated deliberately: the same modification, with a
*& wrong name in the work area. The documentation is explicit - 'The
*& name component must contain the name of the current screen element,
*& otherwise the statement is not executed.'
*&
*& This loop tries to make P_KEEP highlighted, but overwrites name
*& with a value that is never the current element. Nothing happens,
*& and nothing reports that nothing happened.
*&---------------------------------------------------------------------*
  LOOP AT SCREEN INTO DATA(ls_wrong).
    IF ls_wrong-name = 'P_KEEP'.
      ls_wrong-intensified = '1'.
      ls_wrong-name        = 'P_DOES_NOT_EXIST'.   " <- disables it
      MODIFY SCREEN FROM ls_wrong.
    ENDIF.
  ENDLOOP.

*&---------------------------------------------------------------------*
*& Trap 4: required = '2' renders identically to '1' and is never
*& checked. Useful when you want the visual cue without blocking F8 -
*& and a nasty surprise if you believed you had made input mandatory.
*&---------------------------------------------------------------------*
  LOOP AT SCREEN INTO DATA(ls_req).
    IF ls_req-name = 'P_NOTE'.
      ls_req-required = '2'.          " recommended, NOT enforced
      MODIFY SCREEN FROM ls_req.
    ENDIF.
  ENDLOOP.

*&---------------------------------------------------------------------*
*& The function code that made the screen come back.
*&
*& Switching a radio button only re-displays the screen because
*& USER-COMMAND uc1 was declared on it. Without that addition the
*& radio button changes no display state until the user presses Enter,
*& which is the single most common reason a correct
*& AT SELECTION-SCREEN OUTPUT block appears to do nothing.
*&---------------------------------------------------------------------*
AT SELECTION-SCREEN.
  IF sscrfields-ucomm = 'UC1'.
    " Nothing to do. The PBO above re-runs and re-decides everything;
    " this block exists only to document where the code would go.
  ENDIF.

*&---------------------------------------------------------------------*
*& What the loop really saw.
*&---------------------------------------------------------------------*
START-OF-SELECTION.

  DATA(lv_count) = lines( gt_elem ).

  WRITE: / 'PBO passes so far  :', gv_passes.
  WRITE: / 'Elements last pass :', lv_count.
  WRITE: / 'Hide branch active :', p_some.
  SKIP.

  WRITE: /  'NAME', 34 'GRP', 40 'INP', 46 'OUT', 52 'INV', 58 'ACT'.
  ULINE.

  LOOP AT gt_elem INTO DATA(ls_out).
    WRITE: /  ls_out-name(30),
           34 ls_out-group1,
           40 ls_out-input,
           46 ls_out-output,
           52 ls_out-invis,
           58 ls_out-active.
  ENDLOOP.

  SKIP.
  WRITE: / 'Note: the generated element names above (low/high fields,'.
  WRITE: / 'labels, the multiple-selection pushbutton) are not a'.
  WRITE: / 'documented interface. Group by MODIF ID, not by name.'.
