*&---------------------------------------------------------------------*
*& Report YDJ_ENHANCEMENT_DEMO
*&---------------------------------------------------------------------*
*& Enhancement Framework - the pre/post/overwrite exit call chain and
*& the documented rules that decide whether your exit runs at all.
*&
*&   1. CORE_OBJECT       -> the exit is a GENERATED LOCAL CLASS
*&                           lcl_<enh>, so me-> is that local class and
*&                           NOT the object being enhanced. The original
*&                           instance is reachable only as CORE_OBJECT.
*&   2. SIGNATURES CHANGE -> a pre-exit has NO exporting parameters at
*&                           all; a post-exit gets the original's
*&                           EXPORTING as CHANGING (already filled), and
*&                           a RETURNING parameter also becomes CHANGING.
*&   3. ENDMETHOD RULE    -> the post-exit runs "only if the method is
*&                           exited using ENDMETHOD". An exception in
*&                           the pre-exit skips BOTH the method and the
*&                           post-exit; an exception in the method skips
*&                           the post-exit.
*&   4. RETURN IS FINE    -> since NW 7.0 EhP1 / 7.1 EhP1 (SAP Note
*&                           1083387) CHECK, EXIT and RETURN in the
*&                           original do NOT stop the post-exit. Only an
*&                           exception does.
*&   5. OVERWRITE WINS    -> an overwrite-exit runs INSTEAD of the
*&                           original, and cannot coexist with a pre- or
*&                           post-exit on the same method.
*&
*& WHAT THIS PROGRAM IS NOT
*& ------------------------
*& It is not real enhancement syntax. Real pre/post/overwrite exits only
*& exist on GLOBAL classes and are generated by the Class Builder, and
*& ENHANCEMENT / ENDENHANCEMENT "cannot be entered and edited directly"
*& (they are generated by the Workbench). ENHANCEMENT-POINT also needs a
*& real enhancement spot to exist or it is a syntax error, so the two
*& explicit forms appear here as COMMENTED-OUT reference blocks only.
*&
*& What IS runnable is a faithful SIMULATION of the generated structure:
*& lcl_core is the shipped class, lcl_enh stands in for the generated
*& lcl_<enhancement_name> (holding a CORE_OBJECT reference, implementing
*& stand-ins for IPR_/IPO_/IOW_ with the documented signature changes),
*& and lcl_runtime performs the dispatch the framework would perform.
*& The point is to make the CALL SEQUENCE and the INTERRUPTION RULES
*& observable, since those are what the traps are about.
*&
*& Self-contained: local classes and literals only. No DDIC objects, no
*& database access, no writes. Nothing here can terminate the program -
*& every raised exception is caught by the driver on purpose.
*&---------------------------------------------------------------------*
REPORT ydj_enhancement_demo.

TYPES ty_amount TYPE p LENGTH 11 DECIMALS 2.

*&---------------------------------------------------------------------*
*& The reference forms of the two EXPLICIT source code enhancements.
*& Kept commented out: each needs a real enhancement spot in the system.
*&---------------------------------------------------------------------*
*  " ADDS the plug-ins here. Dynamic: stand-by plug-ins are COMPILED IN
*  " but NOT EXECUTED. STATIC would also execute stand-by ones and is
*  " the form intended for DECLARATIONS.
*  ENHANCEMENT-POINT ydj_enh_01 SPOTS ydj_spot.
*
*  " REPLACES the block with exactly ONE plug-in. Without STATIC the
*  " declarative statements are APPENDED rather than replaced, so a
*  " plug-in that re-declares a variable leaves the original DATA line
*  " in place. If no plug-in is found the original block runs.
*  ENHANCEMENT-SECTION ydj_enh_02 SPOTS ydj_spot.
*    lv_rate = '0.10'.
*  END-ENHANCEMENT-SECTION.

*&---------------------------------------------------------------------*
*& A plain exception, so trap 3 can be triggered on demand.
*&---------------------------------------------------------------------*
CLASS lcx_demo DEFINITION INHERITING FROM cx_static_check.
ENDCLASS.

CLASS lcl_enh DEFINITION DEFERRED.

*&---------------------------------------------------------------------*
*& Shared trace, so the CALL SEQUENCE is the thing being observed.
*&---------------------------------------------------------------------*
CLASS lcl_trace DEFINITION.

  PUBLIC SECTION.
    CLASS-DATA gt_lines TYPE STANDARD TABLE OF string WITH EMPTY KEY.
    CLASS-METHODS add   IMPORTING iv_text TYPE string.
    CLASS-METHODS reset.
    CLASS-METHODS dump.

ENDCLASS.

CLASS lcl_trace IMPLEMENTATION.

  METHOD add.
    APPEND iv_text TO gt_lines.
  ENDMETHOD.

  METHOD reset.
    CLEAR gt_lines.
  ENDMETHOD.

  METHOD dump.
    DATA lv_line TYPE string.

    IF gt_lines IS INITIAL.
      WRITE: / '    (nothing ran)'.
      RETURN.
    ENDIF.

    LOOP AT gt_lines INTO lv_line.
      WRITE: / '    ', lv_line.
    ENDLOOP.
  ENDMETHOD.

ENDCLASS.

*&---------------------------------------------------------------------*
*& THE SHIPPED CLASS - stands in for an SAP standard global class.
*& Befriends the enhancement class the way the generated local class is
*& able to reach the original class's components through CORE_OBJECT.
*&---------------------------------------------------------------------*
CLASS lcl_core DEFINITION FRIENDS lcl_enh.

  PUBLIC SECTION.
    METHODS calculate_discount
      IMPORTING iv_amount   TYPE ty_amount
                iv_mode     TYPE c LENGTH 1
      EXPORTING ev_discount TYPE ty_amount
      RAISING   lcx_demo.

  PRIVATE SECTION.
    " Private on purpose: an exit reaches this ONLY via CORE_OBJECT.
    DATA mv_base_rate TYPE ty_amount VALUE '0.10'.

ENDCLASS.

CLASS lcl_core IMPLEMENTATION.

  METHOD calculate_discount.
    CLEAR ev_discount.
    lcl_trace=>add( 'core   : calculate_discount entered' ).

    " Mode X: the original raises. The post-exit will NOT run.
    IF iv_mode = 'X'.
      lcl_trace=>add( 'core   : raising lcx_demo' ).
      RAISE EXCEPTION TYPE lcx_demo.
    ENDIF.

    " Mode R: the original leaves early with RETURN. Since NW 7.0 EhP1
    " this does NOT stop the post-exit (SAP Note 1083387).
    IF iv_mode = 'R'.
      lcl_trace=>add( 'core   : leaving early via RETURN' ).
      RETURN.
    ENDIF.

    ev_discount = iv_amount * mv_base_rate.
    lcl_trace=>add( 'core   : reached ENDMETHOD' ).
  ENDMETHOD.

ENDCLASS.

*&---------------------------------------------------------------------*
*& Stand-ins for the three GENERATED interfaces. The signatures below
*& are not a simplification - they are the documented transformation:
*&   pre       : no EXPORTING parameters at all
*&   post      : EXPORTING becomes CHANGING (and RETURNING too)
*&   overwrite : identical to the original method
*&---------------------------------------------------------------------*
INTERFACE lif_ipr_pre.          " IPR_<enhancement_name>
  METHODS calculate_discount
    IMPORTING iv_amount TYPE ty_amount
              iv_mode   TYPE c LENGTH 1
    RAISING   lcx_demo.
ENDINTERFACE.

INTERFACE lif_ipo_post.         " IPO_<enhancement_name>
  METHODS calculate_discount
    IMPORTING iv_amount   TYPE ty_amount
    CHANGING  cv_discount TYPE ty_amount.
ENDINTERFACE.

INTERFACE lif_iow_overwrite.    " IOW_<enhancement_name>
  METHODS calculate_discount
    IMPORTING iv_amount   TYPE ty_amount
              iv_mode     TYPE c LENGTH 1
    EXPORTING ev_discount TYPE ty_amount
    RAISING   lcx_demo.
ENDINTERFACE.

*&---------------------------------------------------------------------*
*& THE GENERATED ENHANCEMENT CLASS - lcl_<enhancement_name>.
*& Note core_object: inside a real exit, me-> refers to THIS class and
*& not to the object being enhanced, which is the whole of trap 1.
*&---------------------------------------------------------------------*
CLASS lcl_enh DEFINITION.

  PUBLIC SECTION.
    INTERFACES: lif_ipr_pre,
                lif_ipo_post,
                lif_iow_overwrite.

    METHODS constructor IMPORTING io_core TYPE REF TO lcl_core.

    " Deliberately same name as the original's private attribute, to
    " show that me->mv_base_rate is NOT the enhanced object's value.
    DATA mv_base_rate TYPE ty_amount VALUE '0.99'.

  PRIVATE SECTION.
    DATA core_object TYPE REF TO lcl_core.

ENDCLASS.

CLASS lcl_enh IMPLEMENTATION.

  METHOD constructor.
    core_object = io_core.
  ENDMETHOD.

  METHOD lif_ipr_pre~calculate_discount.
    DATA lv_mine TYPE ty_amount.
    DATA lv_core TYPE ty_amount.

    lv_mine = mv_base_rate.                 " the LOCAL class's value
    lv_core = core_object->mv_base_rate.    " the ENHANCED object's value

    lcl_trace=>add( |pre    : me->mv_base_rate = { lv_mine }| ).
    lcl_trace=>add( |pre    : core_object->mv_base_rate = { lv_core }| ).

    " A pre-exit has no EXPORTING and no RETURNING - it cannot change
    " the result. Raising is the only way it can alter the outcome, and
    " it suppresses the original AND the post-exit together.
    IF iv_mode = 'P'.
      lcl_trace=>add( 'pre    : raising lcx_demo' ).
      RAISE EXCEPTION TYPE lcx_demo.
    ENDIF.

    lcl_trace=>add( 'pre    : reached ENDMETHOD' ).
  ENDMETHOD.

  METHOD lif_ipo_post~calculate_discount.
    " cv_discount ARRIVES FILLED with whatever the original produced.
    " Assigning unconditionally would overwrite the standard result;
    " this adds a cap instead, leaving the standard value where it is
    " already acceptable.
    DATA lv_cap TYPE ty_amount.

    lcl_trace=>add( |post   : received cv_discount = { cv_discount }| ).

    lv_cap = iv_amount * '0.05'.
    IF cv_discount > lv_cap.
      cv_discount = lv_cap.
      lcl_trace=>add( |post   : capped to { cv_discount }| ).
    ELSE.
      lcl_trace=>add( 'post   : standard result left unchanged' ).
    ENDIF.
  ENDMETHOD.

  METHOD lif_iow_overwrite~calculate_discount.
    " Runs INSTEAD of the original. Every future SAP correction to
    " lcl_core->calculate_discount is now dead code.
    CLEAR ev_discount.
    ev_discount = iv_amount * '0.25'.
    lcl_trace=>add( |over   : original NOT called, discount = { ev_discount }| ).
  ENDMETHOD.

ENDCLASS.

*&---------------------------------------------------------------------*
*& The dispatch the framework performs. The interruption rules are not
*& coded as special cases - they fall out of ordinary exception
*& propagation, which is exactly how the real chain behaves.
*&---------------------------------------------------------------------*
CLASS lcl_runtime DEFINITION.

  PUBLIC SECTION.
    CLASS-METHODS dispatch
      IMPORTING io_core      TYPE REF TO lcl_core
                io_enh       TYPE REF TO lcl_enh
                iv_amount    TYPE ty_amount
                iv_mode      TYPE c LENGTH 1
                iv_overwrite TYPE abap_bool DEFAULT abap_false
      EXPORTING ev_discount  TYPE ty_amount
      RAISING   lcx_demo.

ENDCLASS.

CLASS lcl_runtime IMPLEMENTATION.

  METHOD dispatch.
    CLEAR ev_discount.

    " An overwrite-exit excludes pre- and post-exits on the same method.
    IF iv_overwrite = abap_true.
      io_enh->lif_iow_overwrite~calculate_discount(
        EXPORTING iv_amount   = iv_amount
                  iv_mode     = iv_mode
        IMPORTING ev_discount = ev_discount ).
      RETURN.
    ENDIF.

    " 1. pre-exit. If it raises, nothing below runs.
    io_enh->lif_ipr_pre~calculate_discount( iv_amount = iv_amount
                                            iv_mode   = iv_mode ).

    " 2. the original method. If it raises, the post-exit is skipped.
    io_core->calculate_discount( EXPORTING iv_amount   = iv_amount
                                           iv_mode     = iv_mode
                                 IMPORTING ev_discount = ev_discount ).

    " 3. post-exit - reached only because ENDMETHOD was reached above.
    io_enh->lif_ipo_post~calculate_discount(
      EXPORTING iv_amount   = iv_amount
      CHANGING  cv_discount = ev_discount ).
  ENDMETHOD.

ENDCLASS.

*&---------------------------------------------------------------------*
*& Driver
*&---------------------------------------------------------------------*
CLASS lcl_demo DEFINITION.

  PUBLIC SECTION.
    CLASS-METHODS run.

  PRIVATE SECTION.
    CLASS-METHODS scenario
      IMPORTING iv_title     TYPE string
                iv_mode      TYPE c LENGTH 1
                iv_overwrite TYPE abap_bool DEFAULT abap_false.

ENDCLASS.

CLASS lcl_demo IMPLEMENTATION.

  METHOD scenario.
    DATA lo_core     TYPE REF TO lcl_core.
    DATA lo_enh      TYPE REF TO lcl_enh.
    DATA lv_discount TYPE ty_amount.
    DATA lv_amount   TYPE ty_amount VALUE '1000.00'.
    DATA lv_failed   TYPE abap_bool.

    CREATE OBJECT lo_core.
    CREATE OBJECT lo_enh EXPORTING io_core = lo_core.

    lcl_trace=>reset( ).
    lv_failed = abap_false.

    TRY.
        lcl_runtime=>dispatch( EXPORTING io_core      = lo_core
                                         io_enh       = lo_enh
                                         iv_amount    = lv_amount
                                         iv_mode      = iv_mode
                                         iv_overwrite = iv_overwrite
                               IMPORTING ev_discount  = lv_discount ).
      CATCH lcx_demo.
        lv_failed = abap_true.
    ENDTRY.

    SKIP.
    WRITE: / iv_title.
    lcl_trace=>dump( ).

    IF lv_failed = abap_true.
      WRITE: / '    result  : exception propagated to the caller'.
    ELSE.
      WRITE: / '    result  :', lv_discount.
    ENDIF.
  ENDMETHOD.

  METHOD run.
    DATA lv_amount TYPE ty_amount VALUE '1000.00'.

    WRITE: / 'Enhancement Framework - pre / post / overwrite call chain'.
    WRITE: / 'Amount:', lv_amount, '   standard rate 10%, post-exit caps at 5%'.
    ULINE.

    " Normal run: the full chain, and the post-exit caps 100.00 to 50.00.
    scenario( iv_title = 'A. Normal - pre, original, post all run'
              iv_mode  = space ).

    " Trap 3, first half: the pre-exit raises, so the original never
    " runs and neither does the post-exit.
    scenario( iv_title = 'B. Exception in the PRE-exit - original and post skipped'
              iv_mode  = 'P' ).

    " Trap 3, second half: the original raises, so the post-exit is
    " skipped. This is the real reason a post-exit "does nothing".
    scenario( iv_title = 'C. Exception in the ORIGINAL - post skipped'
              iv_mode  = 'X' ).

    " Trap 4: an early RETURN is NOT an exception. The post-exit still
    " runs - on a zero result, which is its own kind of surprise.
    scenario( iv_title = 'D. RETURN in the ORIGINAL - post STILL runs (Note 1083387)'
              iv_mode  = 'R' ).

    " Trap 5: the overwrite-exit replaces the original entirely.
    scenario( iv_title     = 'E. Overwrite-exit - original never called, no pre/post allowed'
              iv_mode      = space
              iv_overwrite = abap_true ).

    SKIP.
    ULINE.
    WRITE: / 'Reminder: a post-exit is the SUCCESS path only. It is not a'.
    WRITE: / 'CLEANUP block and not a finally - an exception anywhere'.
    WRITE: / 'before it means it does not run at all.'.
  ENDMETHOD.

ENDCLASS.

START-OF-SELECTION.
  lcl_demo=>run( ).
